###############################################################
#  Generated by:      Cadence Innovus 21.17-s075_1
#  OS:                Linux x86_64(Host ID fastx3-25.ews.illinois.edu)
#  Generated on:      Sat Apr 27 00:07:48 2024
#  Design:            cpu
#  Command:           saveDesign cpu
###############################################################
current_design cpu
